### ISSUE TITLE
Change RPC

### ISSUE THREAD

**Issue by pool2mine** [xops/expedition#10]
Hi, i am running the explorer in a VM, i have my ETC blockchain in a separarate VM in the same LAN. i see the explorer takes some time to load, so i wanted to use my own node so it can load stats faster. i tried to change useChainList.ts but i can't connect to the node... i used private ip, public ip, ":port", no port, i don't know how to make it work, i still get the message "invalid RPC url" when i open the website. what would be the correct way to do it? thanks in advance!

**Comment by entmike** [comment]
I have this same problem.  I've tried specifying the environment variable `REACT_APP_ETH_RPC_URL` as well as URL parameter `rpcUrl` and they both do not access my local `geth` RPC-enabled client.

**Comment by pool2mine** [comment]
Well seems like blockscout has better performance... you download the entire blockchain in a local database so you don't have to read remotely

**Comment by jianchengwang** [comment]
`geth --rpccorsdomain "*"` allow Cross-domain
it is ok for me

**Comment by shanejonas** [comment]
Looks like you need to enable rpc cors domain. Open a new issue if it persists
