### ISSUE TITLE
Hyperledger Besu RPC API <-> Expedition

### ISSUE THREAD

**Issue by DRIgnazGortngschirl** [xops/expedition#12]
Hello !

I am running a Hyperledger Besu node and I would like to use the RPC API offered Besu for Expedition. Sadly I am not able to do this.

**Details:**
Using my own project: [Hyperledger Besu Node](https://github.com/MrMarioMichel/hyperledger-besu-etc-node)
Besu Version: [v21.10.2](https://github.com/hyperledger/besu/releases/tag/21.10.2)
Expedition Version: Just did built it yesterday via the Dockerfile

**Potential Issue**

I guess this incomparability/not working is because for example the response from ethercluster.com is a simple one line and the Besu API response is a formatted answer. 
![img](https://pics.mariomichel.com/8m53fu.png)

Or is there any other issue I am missing

Thanks!

BTW: How can I change the Progress Bar and stats colour ?  Thanks!

![img](https://pics.mariomichel.com/exiq8b.png)

**Comment by MrMarioMichel** [comment]
Update pics as link was lost

**Comment by DRIgnazGortngschirl** [comment]
Was solved, Cors Problem. :|
