### ISSUE TITLE
setting rpc from url no longer works

### ISSUE THREAD

**Issue by BelfordZ** [xops/expedition#7]
we should be able to set the rpcUrl in a link as follows: `https://expedition.dev/?rpcUrl=https://www.ethercluster.com/etc`

Since adding the chain list feature, this no longer works because we are missing name & network. 

If we add `name` and `network` to the url params, then we could add the chain to the list, and when we save to localstorage, it will end up always in the list.

**Comment by BelfordZ** [comment]
idea from shane: 
> if it has no name maybe make it `Custom Network`

network default to ... `Unknown`

**Comment by BelfordZ** [comment]
additionally, if name and network are missing, we could open the 'add chain' modal and have the user add a name and network

**Comment by dylankilkenny** [comment]
@BelfordZ any update on this? trying to run locally pointed at a local node but it just redirects to ETC.

setting REACT_APP_ETH_RPC_URL also not working
